fix neutralization
drivers/base/core.c:1078:21: error: use of undeclared identifier 'DL_FLAG_SYNC_STATE_ONLY'
                    link->flags & DL_FLAG_SYNC_STATE_ONLY)

Due to DL_FLAG Errors, i would temporarily leave it there for a moment till i can fully cherry-pick whats needed since i only cherry-pick the minimal ones

Another Point of note: Some components are stuck under 111, i think i should add a string on that??